- name: Instalar Servidor Docker
  hosts: server01
  become: 'yes'
  tasks:
    - name: Instalar Dependencias
      apt:
        name: ['ca-certificates', 'curl', 'gnupg']
        state: present
        update_cache: 'yes'
    - name: Adicionar Chave GPG
      apt_key:
        url: 'https://download.docker.com/linux/debian/gpg'
        state: present
    - name: Adicionar Repositorio
      apt_repository:
        repo: 'deb https://download.docker.com/linux/debian bullseye stable'
        state: present
    - name: Instalar Docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
        update_cache: 'yes'
    - name: Habilitar Docker
      service:
        name: docker
        state: started
        enabled: 'yes'
