- name: Remover Servidor Docker
  hosts: servers
  become: 'yes'
  gather_facts: 'no'
  tasks:
    - name: Desabilitar Docker
      service:
        name: docker
        state: stopped
        enabled: 'no'
      ignore_errors: 'yes'
    - name: Remover Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: absent
        purge: 'yes'
    - name: Remover Repositorio
      apt_repository:
        repo: 'deb https://download.docker.com/linux/debian bullseye stable'
        state: absent
    - name: Remover Dependencias
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
        state: absent
