- name: Instalar Servidor Web
  hosts: servers
  become: 'yes'
  tasks:
  - name: Instalar Nginx
    apt:
      name: nginx
      state: present
  - name: Habilitar Nginx
    service:
      name: nginx
      state: started
      enabled: 'yes'
