- name: Remover Servidor Web
  hosts: servers
  become: 'yes'
  gather_facts: 'no'
  tasks:

  - name: Parar Nginx
    service:
      name: nginx
      state: stopped
      enabled: 'no'
    ignore_errors: 'yes'

  - name: Remover Nginx
    apt:
      name: ['nginx', 'nginx-common']
      state: absent
